### ISSUE TITLE
Quad pingable lfo module causing vcv crash

### ISSUE THREAD

**Issue by offthesky** [4ms/4ms-vcv#11]
using the latest dev build 2.0.1, vcv 2.5.2, windows 11(latest)

[4ms quad pingable lfo causes crash.zip](https://github.com/user-attachments/files/16768190/4ms.quad.pingable.lfo.causes.crash.zip)

if i load up the above patch and select an audio driver, vcv crashes. tested on 2 different laptops. seems to only crash if the cable is connected to any of the ping inputs

edit: not sure if this info helps but if i add a bog cvd (wet 100%) with a cable from the multi lfo going into the cvd and out from cvd into the ping input, it seems to not crash when patch is loaded up

**Comment by danngreen** [comment]
Thanks. I can reproduce it on Windows 11 only. Seems to be another version of the PEG/MPEG bug. I'm going to do a more detailed check for this on all modules...

**Comment by audiobird** [comment]
I can reproduce this on Linux using the patch @offthesky provided.

If I disconnected the patch cable, select an audio driver, and then reconnect the cable there is no crash. I can even select a new audio driver without a problem after that.

**Comment by danngreen** [comment]
OK

**Comment by danngreen** [comment]
Fixed: it was a similar bug to #9. Also looked at all the modules and hopefully caught future bugs of the same type.

Please re-open if this doesn't fix it for you!
