### ISSUE TITLE
Ensemble Osc. has clicks/transients on changing v/oct input

### ISSUE THREAD

**Issue by VegaDeftwing** [4ms/4ms-vcv#13]
I'll collect more information, including scope captures of what I'm seeing, later and edit this issue. I just wanted to get the issue made so you could at least try to reproduce your side.

In short, I hear clicks or transients that I don't on the hardware version when sending pitch changes to the V/Oct input.

System:
 OS: Windows 11 22H2 (22621.2428)
CPU: Ryzen 5900x
GPU: Nvidia 3090

Rack settings:
Version: Pro 2.5.2
Sample rate: 44.1
Buffer size: 256

**Comment by danngreen** [comment]
Yes, please post steps to reproduce. I tried a few things and am not seeing anything unusual. You know about the right-click Alt Param for Crossfade? If the Crossfade setting is low, there are clicks when Root CV causes the notes to change (which is the whole point of Crossfade).

**Comment by VegaDeftwing** [comment]
You're correct, it's on the Root CV, not the Pitch. I didn't catch that before. The clicks are definitely more noticeable than on hardware. The crossfade is at 0.5. At 1, I don't hear any clicks. Since I have a hardware module, I tested with the same settings as the module in VCV, and I definitely hear the click much louder from the software module. I have crossfade down at 0 now to test both, to make it as apparent as possible. I have some attuverters in line with the root input both in VCV and in hardware so I can get them to match as much as possible (I didn't calibrate on the output to my FH-2 for this quick test)

<img width="1574" alt="image" src="https://github.com/user-attachments/assets/accb5d57-fecb-476b-9c6f-200517f5ecb9">

I'm out of time on my lunch break, I'll get a recording later.

**Comment by danngreen** [comment]
OK, yes I think I hear that now. It goes away with Crossfade at 1, but at 0.5 it's more like hardware sounds at 0.2 or something. I'll look into it

**Comment by danngreen** [comment]
Ok I think I have this fixed. The Root CV jack was not being updated at the same rate as on hardware, and there were some digital filters added to the hardware firmware that hadn't been pulled into the vcv version yet. It sounds pretty close now. 
Let me know if you can test it, builds are here:
https://github.com/4ms/4ms-vcv/releases/tag/vcv-v0.0.0

**Comment by VegaDeftwing** [comment]
Yep! Seems perfect now, and sounds *much* better IMHO. Thank you so much!
