### ISSUE TITLE
Hub Save Button not working sometimes, and Loading a Preset causes a crash

### ISSUE THREAD

**Issue by Deniou** [4ms/4ms-vcv#23]
Hi,
I just made the update to V. 2.0.5 .
Since then, I cannot save modifications on previously existing patches in vcv rack (save button on the meta virtual module does nothing). It seems to work on new patches though.
Thank you.
Denis

**Comment by Deniou** [comment]
HI,
I tried to save the state OF MM as a preset and open it in a new patch. That makes vcv crash. 
Cheers
Denis

**Comment by Deniou** [comment]
Well... a bunch of hours later.... It seems to work again.... It seems it's related to the play status of the patch. When its not playing, due to a false inerface setting or whatever, the buttons don't play as well... if it make sense.
but loading a preset still makes vcv crash.

**Comment by Deniou** [comment]
Hi Dan
Thanks for your reply
No, I didn't post it in the forum.
The thing about the save button on MM.... I'm not sure it's really an issue
(see the second comment on Github.)
But I think there's really a problem on the preset side. Loading a preset
previously saved make vcv crash.
I'm on Windows 11.
Anyway. I'm building a 4op synth voice that I will play with my trumpet
with the help of the interface of sonicsmith... I'm really looking forward
to give a test. ;)
Have a nice one
Cheers
Denis




Denis Tercier
Rue du Centre 22
1131 Tolochenaz
+41 79 239 96 77

**Comment by danngreen** [comment]
Ok, thanks. 
Yes, there's no preset functionality in the MetaModule Hub. So that won't work. I'll why it's crashing.

Another user reported the save button not working. Can you elaborate more what you mean by this:

>It seems it's related to the play status of the patch. When its not playing, due to a false inerface setting or whatever, the buttons don't play as well.

**Comment by Deniou** [comment]
It's just a hypothesis.
In the patch in which it happened, there was an audio module. But this
time, my computer was not connected to my audio interface. I was working on
labeling knobs so I didn't need to modify the setting of the audio module
and so, the patch didn't "play". And when I wanted to save the .yml file It
simply didn't work ("play"). Does it make any sense to you?
Denis Tercier
Rue du Centre 22
1131 Tolochenaz
+41 79 239 96 77

**Comment by danngreen** [comment]
Ok, thanks I understand.

**Comment by danngreen** [comment]
Hub button saving should be fixed with this commit: c3652ec5ade7a2cdd5e8960b5cae3dc404198496
Loading presets fixed with this: f3cc1b9ee692a8ba3d11a6b73e234b9116704aa6

Both these are present in v2.0.6
