### ISSUE TITLE
Crash with the Djembe module when white noise is applied to the pitch input

### ISSUE THREAD

**Issue by musicalentropy** [4ms/4ms-vcv#25]
Hello to the 4ms team! Ivan / musicalentropy here.

Been playing a bit with all the 4ms modules in VCV Rack, and I came upon an issue which causes crashes in the Djembe module. When one plays with it when it makes sound with the right input parameters (say default parameters + a bit of sharpness), if white noise is being applied to the pitch input (for example from the VCV noise module, white output), then the module crashes and do not recover at all until it is reset even if the noise is removed. The output just returns a NaNV.

It happens on 2.0.6, and was present in previous versions.

**Comment by danngreen** [comment]
Thanks, I can confirm this, also on hardware.

**Comment by danngreen** [comment]
OK, fixed in core modules:
https://github.com/4ms/metamodule-core-modules/commit/7523f74728d3725279d76d1ffb26bd493e9db7e3
