### ISSUE TITLE
Verb module doesn't have any label

### ISSUE THREAD

**Issue by musicalentropy** [4ms/4ms-vcv#26]
Hello everybody!

On 2.0.6, I don't remember if it was the case before, I have remarked on VCV Rack Windows that the Verb module doesn't have any label displayed.

![image](https://github.com/user-attachments/assets/a95c285b-9a24-454f-acb2-3e6a78113367)

**Comment by danngreen** [comment]
Fixed in 9200c941ec09a22a9aa6dd04c60504caf7f418e6
