### ISSUE TITLE
Does not install on VCV Rack Pro 2.5.2 Linux Mint (latest stable release and up to date)

### ISSUE THREAD

**Issue by Stubs42** [4ms/4ms-vcv#30]
After adding 4ms modules to my selection in the library VCV Rack tries to install 4ms but does not succeed.

**Comment by Stubs42** [comment]
Download the plugin from your github release worked. So the plugin library build for linux is broken.

**Comment by danngreen** [comment]
Thanks. I have submitted v2.0.8 to the Library, so we should see it soon.
