### ISSUE TITLE
Issues with the LPG 4ms VCV rack module

### ISSUE THREAD

**Issue by musicalentropy** [4ms/4ms-vcv#35]
Hello again! Still playing with the new 4ms VCV Rack modules ;)

Today I have done a few comparisons between several LPG modules designs, so I played with yours and noticed two issues:

* the module doesn't have the tag "Low-pass Gate" which is very useful here
* I think the volume knob on the top is not doing anything, neither is the level CV input

Ivan

**Comment by danngreen** [comment]
Hi, thanks, yes we had mistakenly tagged it as "LPG", not "Low-pass gate", and VCV ignored the unknown tag. Thanks for reporting that.

And the Level knob and CV work on MetaModule hardware, but I see that they have an issue when run on VCV. They actually work if you haven't yet patched the Ping input, but once you patch a cable into that jack then the Level parameter stops working (on VCV only -- all seems well on hardware). Thanks for the report

**Comment by danngreen** [comment]
Ok, just fixed the bug in main -- it'll show up in the next release
