### ISSUE TITLE
your vcvrack modules doesn't show on High Sierra macOS

### ISSUE THREAD

**Issue by higaru2** [4ms/4ms-vcv#6]
vcvrack modules doesn't show 
on old intel based mac 
with macOS High Sierra.

maybe it can be fixed...
thnx

**Comment by higaru2** [comment]
latest 4ms from Releases! latest vcvrack2 pro. x86 ofcourse.
this is from error log:

[3.807 info src/plugin.cpp:167 loadPlugin] Loading plugin from
/Users/wakax/Library/Application Support/Rack2/plugins-mac-x64/4msCompany
[3.820 warn src/plugin.cpp:233 loadPlugin] Could not load plugin
/Users/wakax/Library/Application Support/Rack2/plugins-mac-x64/4msCompany:
Failed to load library /Users/wakax/Library/Application
Support/Rack2/plugins-mac-x64/4msCompany/plugin.dylib:
dlopen(/Users/wakax/Library/Application
Support/Rack2/plugins-mac-x64/4msCompany/plugin.dylib, 6): Symbol not
found: ____chkstk_darwin
  Referenced from: /Users/wakax/Library/Application
Support/Rack2/plugins-mac-x64/4msCompany/plugin.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/wakax/Library/Application
Support/Rack2/plugins-mac-x64/4msCompany/plugin.dylib

thanks Dan!!!!!

**Comment by higaru2** [comment]
thank you!
it could be smth in the compiler

**Comment by danngreen** [comment]
OK yes, now I remember. The build flags specify a minimum of macos 10.15. I don't have access to anything older than that, so I can't test it.
I will see if I can figure out how to lower this, though for now that would be the minimum os version (macOS Catalina)

**Comment by danngreen** [comment]
I tried something simple (adding `-fno-stack-check` to the build flags).
Can you try this version?
https://github.com/4ms/4ms-vcv/actions/runs/10493661605/artifacts/1838357753

**Comment by higaru2** [comment]
i ll be home in 3-4 hours
and i ll try!
thnx

**Comment by higaru2** [comment]
Nysthi plugins maker
on vcvrack forum
had the same issue
with his plugs

ask maybe he can hlp

**Comment by higaru2** [comment]
hurray!
bigups Dan.
it works now:)
problem solved!
many with old machines like me
will be very grateful!!!!!!!!!

thanks!

**Comment by danngreen** [comment]
Wow, I wasn't expecting it to be that easy, but... hooray!
I'll merge that in and close this.
